config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/login', to: 'home#new'

  get 'sign_up', to: 'user#new'
  post 'sign_up', to: 'user#create'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'

  get 'weather' => 'weather#home'
  get 'weather_data' => 'weather#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,

            uniqueness: { case_sensitive: false },

            length: { maximum: 105 },

            format: { with: VALID_EMAIL_REGEX }

  validates :password, presence: true,
            length: { minimum:5, maximum: 16 }

  validate :password_matches_confirmation

  def authenticate(password)
    return true if self.password == password
  end

  private

  def password_matches_confirmation
    if password != password_confirmation
      errors.add(:password, " must match password confirmation")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render 'home/new'
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :require_user, except: [:new, :create]

  def new
    # Display the login form
  end

  def create
    # Authenticate user and set session if successful
    if params[:username].present? && params[:password].present?
      user = User.find_by_email(params[:username])
      if user && user.authenticate(params[:password])
        log_in(user.id)
        flash[:success] = 'Logged In successfully.'
        redirect_to weather_path
      else
        flash[:error] = 'Invalid username or password'
        render 'home/new'
      end
    else
      flash[:error] = 'Invalid username or password'
      render 'home/new'
    end
  end

  def destroy
    # Log out the user by clearing the session
    log_out
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    begin
      @user = User.new(user_params)
      if @user.save!
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
    rescue Exception => e
      Rails.logger.error"----Exception::#{e.message}"
      flash[:error] = e.message
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  before_action :require_user

  require 'net/http'
  require 'uri'
  #make api call to OpenWeathermap api to get json data
  def show
    api_key = 'b0dcda1ff0e8c309df7dce613d3d6992' #api_key can be stored in ENV variables or in database for security purose
    city = params[:city_name]

    url = "https://api.openweathermap.org/data/2.5/weather?q=#{city}&appid=#{api_key}"
    uri = URI(url)

    response = Net::HTTP.get(uri)
    @weather_data = JSON.parse(response)
    puts @weather_data
    if @weather_data["cod"] == 200
      render 'weather/weather_data'
    else
      flash[:error] = 'Could not find entered city in our database.'
      render 'weather/weather'
    end
  end

  def home
    render 'weather/weather'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def log_in(id)
    session[:user_id] = id
  end

  def log_out
    session.delete(:user_id)
    flash[:success] = 'You have logged out.'
    redirect_to login_path
  end

  def require_user
    if !logged_in?
      flash[:error] = "Please log in to do this action"
      redirect_to root_path
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
         <div class="card mt-5">
            <div class="card-header text-center"><h2>Login<h2></div>
              <div class="card-body">
              <%= form_tag(login_path) do %>
                <div class="form-group text-center">
                <%= label_tag 'Username :' %>
                <%= text_field_tag 'username' %>
              </div>
              <div class="form-group text-center" style="margin-top: 5px;">
                 <%= label_tag 'Password :' %>
                 <%= password_field_tag 'password' %>
              </div>
              <div class="form-group text-center" style="margin-top: 10px;">
                 <%= submit_tag 'Login', class: "btn btn-primary text-left"  %>
                 <%= link_to "Sign-up", sign_up_path, class: "btn btn-success ml-2" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
     rel="stylesheet"
     integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
     crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous">
    </script>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h1>Login</h1>

<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="container">
  <div class="row justify-content-center">
    <%= form_tag(login_path) do %>
      <div class="form-group">
        <%= label_tag 'Username' %>
        <%= text_field_tag 'username' %>
      </div>
      <div class="form-group">
        <%= label_tag 'Password' %>
        <%= password_field_tag 'password' %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Login' %>
      </div>
    <% end %>
  </div>
 </div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
 <div class="alert alert-info mt-4">
   <%= flash[:notice] %>
 </div>

<% end %>
<% if flash[:alert] %>
 <div class='alert alert-warning mt-4'>
   <%= flash[:alert] %>
 </div>

<% end %>

app/views/user/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card mt-5">
        <div class="card-header"><h2>Sign Up<h2></div>
        <div class="card-body">
          <%= form_for @user, url: sign_up_path do |f| %>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <div class="form-group text-center" style="margin-top: 10px;">
              <%= f.submit "Sign Up", class: "btn btn-primary mr-10" %>
              <%= link_to "Login", login_path, class: "btn btn-success ml-5" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/weather/weather.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-6">
         <div class="card mt-5">
         <div class="d-flex justify-content-end" >
                    <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
               </div>
            <div class="card-header text-center"><h2>Get Your Cities Current Weather Report with Just One Click !!!<h2></div>
              <div class="card-body">
              <%= form_with(url: weather_data_path, method: "get", local: true) do %>
                <div class="form-group text-center">
                  <%= label_tag 'City Name :' %>
                  <%= text_field_tag 'city_name' %>
                </div>
                <div class="form-group text-center" style="margin-top: 10px;">
                  <%= submit_tag 'Get Weather Report', class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/weather/weather_data.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
      <h2><%=@weather_data["name"]%>: Current Weather Information</h2>
      <div class="d-flex justify-content-end" >
           <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  <table class="table">
    <tr>
      <th>Coordinates</th>
      <td>Latitude: <%= @weather_data["coord"]["lat"] %></td>
      <td>Longitude: <%= @weather_data["coord"]["lon"] %></td>
    </tr>
    <tr>
      <th>Weather</th>
      <td>Main: <%= @weather_data["weather"][0]["main"] %></td>
      <td>Description: <%= @weather_data["weather"][0]["description"] %></td>
    </tr>
    <tr>
      <th>Main</th>
      <td>Temperature: <%= @weather_data["main"]["temp"] %> K</td>
      <td>Feels Like: <%= @weather_data["main"]["feels_like"] %> K</td>
      <td>Pressure: <%= @weather_data["main"]["pressure"] %> hPa</td>
      <td>Humidity: <%= @weather_data["main"]["humidity"] %> %</td>
    </tr>
    <tr>
      <th>Wind</th>
      <td>Speed: <%= @weather_data["wind"]["speed"] %> m/s</td>
      <td>Deg: <%= @weather_data["wind"]["deg"] %> degrees</td>
    </tr>
  </table>
  <%= link_to 'Back to Weather Page', weather_path, class: "btn btn-secondary text-center" %>
</div>